export const metadata = {
    title: "About",
    description: "Generated by Next.js",
};

export default function Page() {
    return (
        <div>
            {/* <Navigation /> */}
            <h1>About Page</h1>
        </div>
    );
}
