export const metadata = {
    title: "Cabins",
    description: "Generated by Next.js",
};

export default function Page() {
    return (
        <div>
            <h1>Cabins Page</h1>
        </div>
    );
}
