export const metadata = {
    title: "Guest Area",
    description: "Generated by Next.js",
};

export default function Page() {
    return (
        <div>
            {/* <Navigation /> */}
            <h1>Account Page</h1>
        </div>
    );
}
