export const metadata = {
    title: "Guest Area",
    description: "Generated by Next.js",
};

export default function Page() {
    return (
        <div>
            {/* <Navigation /> */}
            <h2 className="font-semibold text-2xl text-accent-400 mb-7">
                Welcome, Kadir
            </h2>
        </div>
    );
}
